#!/usr/bin/env bash
PROJDIR=/home/acalc79/synced/part-ii-project
DATARELDIR=data
LOGRELDIR=logs
OUTRELDIR=out
SCRIPTRELDIR=dlti_scripts
DATADIR=$PROJDIR/$DATARELDIR
LOGDIR=$PROJDIR/$LOGRELDIR
OUTDIR=$PROJDIR/$OUTRELDIR
SCRIPTDIR=$PROJDIR/$SCRIPTRELDIR
